# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Eena Kosik
name: Eena Kosik
email: eena.kosik@gmail.com
locale: 'en-US'
words_per_minute: 200

# Search
search: true
lunr:
  search_within_pages: true

include:
  - _pages
  - assets

# exlude:

plugins:
  - jekyll-feed
  - jekyll-include-cache

# Build Settings
markdown: kramdown
minimal_mistakes_skin: "contrast"
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-1234567-8"
    anonymize_ip: false # default


# Author Profile Settings
author:
  name   : "Eena Lee Kosik"
  avatar : /assets/images/tokyo_2023.jpg
  bio    : My name is Eena. You can read more about me in the [About me](/about/) section.
  twitter: "eena_kosik"
  linkedin: "ekosik"
  github: "elkosik"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:eena.kosik@gmail.com"


# Footer Settings
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/ekosik/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/eena_kosik"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elkosik"
    - label: "Scholar"
      icon: "fa fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=LsgTxkEAAAAJ&hl=en&oi=ao"



# Defaults
defaults:
# all
  - scope:
      path: ""
    values:
      layout: splash
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|" 
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: false
      comments: # true
      share: true
      related: true
      sidebar:
        nav: "docs"

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
